language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
    - ocaml-native-compilers
    - libgeoip-dev
install: sh -ex ./scripts/travis-install.sh
cache:
  directories:
  - ${HOME}/.opam
script: sh -ex ./scripts/travis-ci.sh
env:
  - OCAML_VERSION=4.07.1
